// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolTag.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProtocolTag_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ProtocolTag_2eproto

#include <limits>
#include <string>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProtocolTag_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtocolTag_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProtocolTag_2eproto;
namespace PacketTag {
class Chat_Normal;
struct Chat_NormalDefaultTypeInternal;
extern Chat_NormalDefaultTypeInternal _Chat_Normal_default_instance_;
class Chat_Whisper;
struct Chat_WhisperDefaultTypeInternal;
extern Chat_WhisperDefaultTypeInternal _Chat_Whisper_default_instance_;
class Exit_Request;
struct Exit_RequestDefaultTypeInternal;
extern Exit_RequestDefaultTypeInternal _Exit_Request_default_instance_;
class Room_User_List;
struct Room_User_ListDefaultTypeInternal;
extern Room_User_ListDefaultTypeInternal _Room_User_List_default_instance_;
}  // namespace PacketTag
PROTOBUF_NAMESPACE_OPEN
template<> ::PacketTag::Chat_Normal* Arena::CreateMaybeMessage<::PacketTag::Chat_Normal>(Arena*);
template<> ::PacketTag::Chat_Whisper* Arena::CreateMaybeMessage<::PacketTag::Chat_Whisper>(Arena*);
template<> ::PacketTag::Exit_Request* Arena::CreateMaybeMessage<::PacketTag::Exit_Request>(Arena*);
template<> ::PacketTag::Room_User_List* Arena::CreateMaybeMessage<::PacketTag::Room_User_List>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PacketTag {

enum PacketType : int {
  CHAT_NORMAL = 0,
  CHAT_WHISPER = 1,
  ROOM_USER_LIST = 2,
  EXIT_REQUEST = 3,
  PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PacketType_IsValid(int value);
constexpr PacketType PacketType_MIN = CHAT_NORMAL;
constexpr PacketType PacketType_MAX = EXIT_REQUEST;
constexpr int PacketType_ARRAYSIZE = PacketType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PacketType_descriptor();
template<typename T>
inline const std::string& PacketType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PacketType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PacketType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PacketType_descriptor(), enum_t_value);
}
inline bool PacketType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PacketType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PacketType>(
    PacketType_descriptor(), name, value);
}
// ===================================================================

class Chat_Normal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PacketTag.Chat_Normal) */ {
 public:
  inline Chat_Normal() : Chat_Normal(nullptr) {}
  ~Chat_Normal() override;
  explicit constexpr Chat_Normal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Chat_Normal(const Chat_Normal& from);
  Chat_Normal(Chat_Normal&& from) noexcept
    : Chat_Normal() {
    *this = ::std::move(from);
  }

  inline Chat_Normal& operator=(const Chat_Normal& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chat_Normal& operator=(Chat_Normal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chat_Normal& default_instance() {
    return *internal_default_instance();
  }
  static inline const Chat_Normal* internal_default_instance() {
    return reinterpret_cast<const Chat_Normal*>(
               &_Chat_Normal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Chat_Normal& a, Chat_Normal& b) {
    a.Swap(&b);
  }
  inline void Swap(Chat_Normal* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chat_Normal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Chat_Normal* New() const final {
    return new Chat_Normal();
  }

  Chat_Normal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Chat_Normal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Chat_Normal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Chat_Normal& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Chat_Normal* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PacketTag.Chat_Normal";
  }
  protected:
  explicit Chat_Normal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_MUST_USE_RESULT std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .PacketTag.PacketType type = 1;
  void clear_type();
  ::PacketTag::PacketType type() const;
  void set_type(::PacketTag::PacketType value);
  private:
  ::PacketTag::PacketType _internal_type() const;
  void _internal_set_type(::PacketTag::PacketType value);
  public:

  // @@protoc_insertion_point(class_scope:PacketTag.Chat_Normal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProtocolTag_2eproto;
};
// -------------------------------------------------------------------

class Chat_Whisper final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PacketTag.Chat_Whisper) */ {
 public:
  inline Chat_Whisper() : Chat_Whisper(nullptr) {}
  ~Chat_Whisper() override;
  explicit constexpr Chat_Whisper(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Chat_Whisper(const Chat_Whisper& from);
  Chat_Whisper(Chat_Whisper&& from) noexcept
    : Chat_Whisper() {
    *this = ::std::move(from);
  }

  inline Chat_Whisper& operator=(const Chat_Whisper& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chat_Whisper& operator=(Chat_Whisper&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Chat_Whisper& default_instance() {
    return *internal_default_instance();
  }
  static inline const Chat_Whisper* internal_default_instance() {
    return reinterpret_cast<const Chat_Whisper*>(
               &_Chat_Whisper_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Chat_Whisper& a, Chat_Whisper& b) {
    a.Swap(&b);
  }
  inline void Swap(Chat_Whisper* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chat_Whisper* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Chat_Whisper* New() const final {
    return new Chat_Whisper();
  }

  Chat_Whisper* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Chat_Whisper>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Chat_Whisper& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Chat_Whisper& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Chat_Whisper* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PacketTag.Chat_Whisper";
  }
  protected:
  explicit Chat_Whisper(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetNicknameFieldNumber = 2,
    kMessageFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // string targetNickname = 2;
  void clear_targetnickname();
  const std::string& targetnickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_targetnickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_targetnickname();
  PROTOBUF_MUST_USE_RESULT std::string* release_targetnickname();
  void set_allocated_targetnickname(std::string* targetnickname);
  private:
  const std::string& _internal_targetnickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetnickname(const std::string& value);
  std::string* _internal_mutable_targetnickname();
  public:

  // string message = 3;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_MUST_USE_RESULT std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .PacketTag.PacketType type = 1;
  void clear_type();
  ::PacketTag::PacketType type() const;
  void set_type(::PacketTag::PacketType value);
  private:
  ::PacketTag::PacketType _internal_type() const;
  void _internal_set_type(::PacketTag::PacketType value);
  public:

  // @@protoc_insertion_point(class_scope:PacketTag.Chat_Whisper)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr targetnickname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProtocolTag_2eproto;
};
// -------------------------------------------------------------------

class Room_User_List final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PacketTag.Room_User_List) */ {
 public:
  inline Room_User_List() : Room_User_List(nullptr) {}
  ~Room_User_List() override;
  explicit constexpr Room_User_List(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Room_User_List(const Room_User_List& from);
  Room_User_List(Room_User_List&& from) noexcept
    : Room_User_List() {
    *this = ::std::move(from);
  }

  inline Room_User_List& operator=(const Room_User_List& from) {
    CopyFrom(from);
    return *this;
  }
  inline Room_User_List& operator=(Room_User_List&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Room_User_List& default_instance() {
    return *internal_default_instance();
  }
  static inline const Room_User_List* internal_default_instance() {
    return reinterpret_cast<const Room_User_List*>(
               &_Room_User_List_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Room_User_List& a, Room_User_List& b) {
    a.Swap(&b);
  }
  inline void Swap(Room_User_List* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Room_User_List* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Room_User_List* New() const final {
    return new Room_User_List();
  }

  Room_User_List* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Room_User_List>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Room_User_List& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Room_User_List& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Room_User_List* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PacketTag.Room_User_List";
  }
  protected:
  explicit Room_User_List(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // .PacketTag.PacketType type = 1;
  void clear_type();
  ::PacketTag::PacketType type() const;
  void set_type(::PacketTag::PacketType value);
  private:
  ::PacketTag::PacketType _internal_type() const;
  void _internal_set_type(::PacketTag::PacketType value);
  public:

  // @@protoc_insertion_point(class_scope:PacketTag.Room_User_List)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProtocolTag_2eproto;
};
// -------------------------------------------------------------------

class Exit_Request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PacketTag.Exit_Request) */ {
 public:
  inline Exit_Request() : Exit_Request(nullptr) {}
  ~Exit_Request() override;
  explicit constexpr Exit_Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Exit_Request(const Exit_Request& from);
  Exit_Request(Exit_Request&& from) noexcept
    : Exit_Request() {
    *this = ::std::move(from);
  }

  inline Exit_Request& operator=(const Exit_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Exit_Request& operator=(Exit_Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Exit_Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const Exit_Request* internal_default_instance() {
    return reinterpret_cast<const Exit_Request*>(
               &_Exit_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Exit_Request& a, Exit_Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Exit_Request* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Exit_Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Exit_Request* New() const final {
    return new Exit_Request();
  }

  Exit_Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Exit_Request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Exit_Request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Exit_Request& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Exit_Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PacketTag.Exit_Request";
  }
  protected:
  explicit Exit_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
  };
  // .PacketTag.PacketType type = 1;
  void clear_type();
  ::PacketTag::PacketType type() const;
  void set_type(::PacketTag::PacketType value);
  private:
  ::PacketTag::PacketType _internal_type() const;
  void _internal_set_type(::PacketTag::PacketType value);
  public:

  // @@protoc_insertion_point(class_scope:PacketTag.Exit_Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProtocolTag_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Chat_Normal

// .PacketTag.PacketType type = 1;
inline void Chat_Normal::clear_type() {
  type_ = 0;
}
inline ::PacketTag::PacketType Chat_Normal::_internal_type() const {
  return static_cast< ::PacketTag::PacketType >(type_);
}
inline ::PacketTag::PacketType Chat_Normal::type() const {
  // @@protoc_insertion_point(field_get:PacketTag.Chat_Normal.type)
  return _internal_type();
}
inline void Chat_Normal::_internal_set_type(::PacketTag::PacketType value) {
  
  type_ = value;
}
inline void Chat_Normal::set_type(::PacketTag::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PacketTag.Chat_Normal.type)
}

// string message = 2;
inline void Chat_Normal::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& Chat_Normal::message() const {
  // @@protoc_insertion_point(field_get:PacketTag.Chat_Normal.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Chat_Normal::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PacketTag.Chat_Normal.message)
}
inline std::string* Chat_Normal::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:PacketTag.Chat_Normal.message)
  return _s;
}
inline const std::string& Chat_Normal::_internal_message() const {
  return message_.Get();
}
inline void Chat_Normal::_internal_set_message(const std::string& value) {
  
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Chat_Normal::_internal_mutable_message() {
  
  return message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Chat_Normal::release_message() {
  // @@protoc_insertion_point(field_release:PacketTag.Chat_Normal.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Chat_Normal::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PacketTag.Chat_Normal.message)
}

// -------------------------------------------------------------------

// Chat_Whisper

// .PacketTag.PacketType type = 1;
inline void Chat_Whisper::clear_type() {
  type_ = 0;
}
inline ::PacketTag::PacketType Chat_Whisper::_internal_type() const {
  return static_cast< ::PacketTag::PacketType >(type_);
}
inline ::PacketTag::PacketType Chat_Whisper::type() const {
  // @@protoc_insertion_point(field_get:PacketTag.Chat_Whisper.type)
  return _internal_type();
}
inline void Chat_Whisper::_internal_set_type(::PacketTag::PacketType value) {
  
  type_ = value;
}
inline void Chat_Whisper::set_type(::PacketTag::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PacketTag.Chat_Whisper.type)
}

// string targetNickname = 2;
inline void Chat_Whisper::clear_targetnickname() {
  targetnickname_.ClearToEmpty();
}
inline const std::string& Chat_Whisper::targetnickname() const {
  // @@protoc_insertion_point(field_get:PacketTag.Chat_Whisper.targetNickname)
  return _internal_targetnickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Chat_Whisper::set_targetnickname(ArgT0&& arg0, ArgT... args) {
 
 targetnickname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PacketTag.Chat_Whisper.targetNickname)
}
inline std::string* Chat_Whisper::mutable_targetnickname() {
  std::string* _s = _internal_mutable_targetnickname();
  // @@protoc_insertion_point(field_mutable:PacketTag.Chat_Whisper.targetNickname)
  return _s;
}
inline const std::string& Chat_Whisper::_internal_targetnickname() const {
  return targetnickname_.Get();
}
inline void Chat_Whisper::_internal_set_targetnickname(const std::string& value) {
  
  targetnickname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Chat_Whisper::_internal_mutable_targetnickname() {
  
  return targetnickname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Chat_Whisper::release_targetnickname() {
  // @@protoc_insertion_point(field_release:PacketTag.Chat_Whisper.targetNickname)
  return targetnickname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Chat_Whisper::set_allocated_targetnickname(std::string* targetnickname) {
  if (targetnickname != nullptr) {
    
  } else {
    
  }
  targetnickname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), targetnickname,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PacketTag.Chat_Whisper.targetNickname)
}

// string message = 3;
inline void Chat_Whisper::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& Chat_Whisper::message() const {
  // @@protoc_insertion_point(field_get:PacketTag.Chat_Whisper.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Chat_Whisper::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PacketTag.Chat_Whisper.message)
}
inline std::string* Chat_Whisper::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:PacketTag.Chat_Whisper.message)
  return _s;
}
inline const std::string& Chat_Whisper::_internal_message() const {
  return message_.Get();
}
inline void Chat_Whisper::_internal_set_message(const std::string& value) {
  
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Chat_Whisper::_internal_mutable_message() {
  
  return message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Chat_Whisper::release_message() {
  // @@protoc_insertion_point(field_release:PacketTag.Chat_Whisper.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Chat_Whisper::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:PacketTag.Chat_Whisper.message)
}

// -------------------------------------------------------------------

// Room_User_List

// .PacketTag.PacketType type = 1;
inline void Room_User_List::clear_type() {
  type_ = 0;
}
inline ::PacketTag::PacketType Room_User_List::_internal_type() const {
  return static_cast< ::PacketTag::PacketType >(type_);
}
inline ::PacketTag::PacketType Room_User_List::type() const {
  // @@protoc_insertion_point(field_get:PacketTag.Room_User_List.type)
  return _internal_type();
}
inline void Room_User_List::_internal_set_type(::PacketTag::PacketType value) {
  
  type_ = value;
}
inline void Room_User_List::set_type(::PacketTag::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PacketTag.Room_User_List.type)
}

// -------------------------------------------------------------------

// Exit_Request

// .PacketTag.PacketType type = 1;
inline void Exit_Request::clear_type() {
  type_ = 0;
}
inline ::PacketTag::PacketType Exit_Request::_internal_type() const {
  return static_cast< ::PacketTag::PacketType >(type_);
}
inline ::PacketTag::PacketType Exit_Request::type() const {
  // @@protoc_insertion_point(field_get:PacketTag.Exit_Request.type)
  return _internal_type();
}
inline void Exit_Request::_internal_set_type(::PacketTag::PacketType value) {
  
  type_ = value;
}
inline void Exit_Request::set_type(::PacketTag::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:PacketTag.Exit_Request.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace PacketTag

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PacketTag::PacketType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PacketTag::PacketType>() {
  return ::PacketTag::PacketType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ProtocolTag_2eproto
